# Generated by Django 4.2 on 2025-07-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='pickup_method',
            field=models.CharField(choices=[('Walk-in', 'Walk-in'), ('Online', 'Online')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='req_type',
            field=models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of Residency', 'Certificate of Residency'), ('Certificate of Indigency', 'Certificate of Indigency'), ('Barangay ID Application', 'Barangay ID Application'), ('Business Clearance / Endorsement', 'Business Clearance / Endorsement'), ('Solo Parent Certificate', 'Solo Parent Certificate'), ('No Derogatory Record', 'No Derogatory Record'), ('Incident Report Copy', 'Incident Report Copy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=50),
        ),
    ]
