# Generated by Django 4.2 on 2025-07-09 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Barangay Hall', max_length=255),
            preserve_default=False,
        ),
    ]
